services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # Explicitly enable the 'ruok' health check command
      ZOO_4LW_COMMANDS_WHITELIST: "ruok"
    ports:
      - "2181:2181"
    networks:
      - ipdr-network
    healthcheck:
      # Use a more reliable bash command to check the TCP port
      test: ["CMD-SHELL", "bash -c 'echo ruok | nc -w 2 localhost 2181'"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - ipdr-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - ipdr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - ipdr-network
    restart: always

  producer:
    build:
      context: .
      dockerfile: ./ipdr_analyzer/producer/Dockerfile
    container_name: producer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - ipdr-network
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: on-failure

  processor:
    build:
      context: .
      dockerfile: ./ipdr_analyzer/processor/Dockerfile
    container_name: processor
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - ipdr-network
    env_file:
      - .env
    restart: on-failure

  consumer:
    build:
      context: .
      dockerfile: ./ipdr_analyzer/consumer/Dockerfile
    container_name: consumer
    depends_on:
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - ipdr-network
    env_file:
      - .env
    restart: on-failure

networks:
  ipdr-network:
    driver: bridge
